### ISSUE TITLE
Uncaught error from thread while running pipeline on card_pipeline_small_test

### ISSUE THREAD

**Issue by nikhita-damaraju** [nanoporegenomics/variant_calling_wf#2]
We're getting the following error while trying to run the pipeline using the command `java -Xmx500g -jar ../cromwell-85.jar run cardEndToEndVcf.wdl --inputs inputs.json` on the card_pipeline_small_test sample:

inputs.json file:
```
{
  "cardEndToEndVcfMethyl.referenceFasta": "../card_pipeline_small_test/chr14.fasta",
  "cardEndToEndVcfMethyl.referenceVntrAnnotations": "../card_pipeline_small_test/human_hs37d5.trf.bed",
  "cardEndToEndVcfMethyl.inputUnphasedMethylBam" : "../card_pipeline_small_test/HG002_Guppy6_cpg_chr14.bam",
  "cardEndToEndVcfMethyl.threads" : 10,
  "cardEndToEndVcfMethyl.referenceName": "grch37_chr14",
  "cardEndToEndVcfMethyl.sampleName": "hg002"
}
```

The output on terminal is:

```
[2023-03-31 16:04:14,42] [info] Running with database db.url = jdbc:hsqldb:mem:beca7322-c088-4f40-8c4f-c526eae8954a;shutdown=false;hsqldb.tx=mvcc
[2023-03-31 16:04:16,41] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2023-03-31 16:04:16,43] [info] [RenameWorkflowOptionsInMetadata] 100%
[2023-03-31 16:04:16,67] [info] Running with database db.url = jdbc:hsqldb:mem:0e6e9d3a-f4a2-4605-9a2d-72a85aad21d3;shutdown=false;hsqldb.tx=mvcc
[2023-03-31 16:04:17,01] [info] Slf4jLogger started
[2023-03-31 16:04:17,15] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-279a2b2",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "failureShutdownDuration" : "5 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2023-03-31 16:04:17,19] [info] Metadata summary refreshing every 1 second.
[2023-03-31 16:04:17,19] [info] No metadata archiver defined in config
[2023-03-31 16:04:17,19] [info] No metadata deleter defined in config
[2023-03-31 16:04:17,20] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2023-03-31 16:04:17,20] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2023-03-31 16:04:17,22] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2023-03-31 16:04:17,27] [info] JobRestartCheckTokenDispenser - Distribution rate: 50 per 1 seconds.
[2023-03-31 16:04:17,29] [info] JobExecutionTokenDispenser - Distribution rate: 20 per 10 seconds.
[2023-03-31 16:04:17,32] [info] SingleWorkflowRunnerActor: Version 85
[2023-03-31 16:04:17,33] [info] SingleWorkflowRunnerActor: Submitting workflow
[2023-03-31 16:04:17,36] [info] Unspecified type (Unspecified version) workflow f67d1a2c-b908-4300-8e83-ee8cf7e20f60 submitted
[2023-03-31 16:04:17,42] [info] SingleWorkflowRunnerActor: Workflow submitted ^[[38;5;2mf67d1a2c-b908-4300-8e83-ee8cf7e20f60^[[0m
[2023-03-31 16:04:17,44] [info] 1 new workflows fetched by cromid-279a2b2: f67d1a2c-b908-4300-8e83-ee8cf7e20f60
[2023-03-31 16:04:17,45] [info] WorkflowManagerActor: Starting workflow ^[[38;5;2mf67d1a2c-b908-4300-8e83-ee8cf7e20f60^[[0m
[2023-03-31 16:04:17,50] [info] WorkflowManagerActor: Successfully started WorkflowActor-f67d1a2c-b908-4300-8e83-ee8cf7e20f60
[2023-03-31 16:04:17,50] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2023-03-31 16:04:17,53] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2023-03-31 16:04:17,62] [info] MaterializeWorkflowDescriptorActor [^[[38;5;2mf67d1a2c^[[0m]: Parsing workflow as WDL 1.0
[2023-03-31 16:04:18,53] [info] Workflow polling stopped
[2023-03-31 16:04:18,53] [^[[38;5;1merror^[[0m] Uncaught error from thread [cromwell-system-akka.dispatchers.engine-dispatcher-52]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[cromwell-system]
java.lang.StackOverflowError: null
        at wdl.transforms.base.ast2wdlom.package$.$anonfun$astNodeToString$1(ast2wdlom.scala:24)
        at scala.Option.map(Option.scala:242)
        at wdl.transforms.base.ast2wdlom.GenericAst.getAttributeAs(GenericAst.scala:67)
        at wdl.transforms.base.ast2wdlom.GenericAst.getAttributeAs$(GenericAst.scala:63)
        at wdl.draft3.transforms.ast2wdlom.Draft3GenericAst.getAttributeAs(Draft3GenericAstNode.scala:7)
        at wdl.transforms.base.ast2wdlom.AstNodeToKvPair$.$anonfun$astNodeToKvPair$1(AstNodeToKvPair.scala:14)
        at common.transforms.package$CheckedAtoB$.$anonfun$runThenCheck$1(package.scala:20)
        at wdl.transforms.base.ast2wdlom.GenericAst.$anonfun$getAttributeAsVector$2(GenericAst.scala:80)
        at cats.data.Chain$.$anonfun$traverseViaChain$3(Chain.scala:795)
        at cats.Eval$.loop$1(Eval.scala:317)
        at cats.Eval$.cats$Eval$$evaluate(Eval.scala:363)
        at cats.Eval$FlatMap.value(Eval.scala:284)
        at cats.data.Chain$.traverseViaChain(Chain.scala:817)
        at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:100)
        at cats.instances.VectorInstances$$anon$1.traverse(vec
.
and 1000 lines more this
```

**Comment by mikolmogorov** [comment]
Hi,

It seems like a chromwell-related error, but it is hard for me to tell what caused it. Could you please share the full error output in a file?

**Comment by nikhita-damaraju** [comment]
Hi,

I've attached the full error output here

[log.txt](https://github.com/nanoporegenomics/card_nanopore_wf/files/11141135/log.txt)

**Comment by mikolmogorov** [comment]
Thanks! The log is pretty cryptic.. Can you try reproducing this tutorial and see if it works for you? https://cromwell.readthedocs.io/en/stable/tutorials/FiveMinuteIntro/ This should rule out the problems on Cromwell side.

**Comment by nikhita-damaraju** [comment]
Hi, 
We tried the pipeline with the example wdl file and cromwell seems to be working alright with this.

```
[2023-04-04 11:46:03,43] [info] SingleWorkflowRunnerActor workflow finished with status 'Succeeded'.
{
  "outputs": {
    "myWorkflow.myTask.out": "hello world"
  },
  "id": "3113971d-b26f-4ba5-afa0-83812cae962e"
}
```

**Comment by nikhita-damaraju** [comment]
UPDATE: we got it to run on the demo file by solving a docker permissions issue.


This error message in the workflow-log file seems to suggest that the user running the docker command does not have permission to connect to the Docker daemon socket. 

1. Check if the user belongs to the docker group and add user to docker
```
$ groups
$ sudo usermod -aG docker $USER
```

2. Check if the Docker daemon is running and run it if not
```
$ sudo systemctl status docker
$ sudo systemctl start docker
```

Thanks!

**Comment by mikolmogorov** [comment]
Glad to hear!
